# Site settings
author: Kelvin Waters
title: Follow the Rabbit: Into Data Science
header-img: img/home-bg.png
email: kelvin.waters@gmail.com
copyright_name: Kelvin Waters
description: > # this means to ignore newlines until "baseurl:"
  A Rabbit Hole Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Kelvincwaters

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
